version: "3.8"
services:
  features-ui:
    build:
      context: Source/features-ui
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./Source/features-ui:/usr/app
      - /usr/app/node_modules
  samples-web:
    build:
      context: Samples/Front
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - 3000:3000
    volumes:
      - ./Samples/Front:/usr/app
      - /usr/app/node_modules
      - /usr/app/.next
    depends_on:
      - samples-api
  samples-api:
    build:
      context: Samples/Back
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://*:5001
    ports:
      - 5001:5001
    volumes:
      - ./Samples/Back:/usr/app
      - ./Source/FeatureManagement.UI:/Source/FeatureManagement.UI
    depends_on:
      - samples-db
  samples-db:
    build:
      context: Samples/Data
      dockerfile: Dockerfile
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "sampl3-db"
    ports:
      - 1433:1433
    volumes:
      - ./Samples/Data:/usr/config
