name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.101

      - name: Yarn install
        run: yarn install
        working-directory: ./Source/features-ui

      - name: Yarn build (features-ui)
        run: yarn build
        working-directory: ./Source/features-ui

      - name: DotNet Build (AspNetCore.FeatureManagement.UI)
        run: dotnet build --configuration Release

      - name: DotNet Test (AspNetCore.FeatureManagement.UI)
        run: dotnet test --no-restore --verbosity normal
